FROM alpine:latest

LABEL img=Server
LABEL dev=Sergii

RUN apk update

COPY server.sh /opt/server.sh
RUN chmod +x /opt/server.sh

ENTRYPOINT ["sh", "/opt/server.sh"]
#CMD ["echo", "--- Server docker ---"]

